### ISSUE TITLE
Rewrite aggregation scheduling for consistency and predictability

### ISSUE THREAD

**Issue by emgrav** [famedly/barad-dur#72]
The stats aggregation statements currently run on a timer, once every 86400 seconds. This is not ideal as there will be scheduling drift, and it's unclear when during the day the aggregation will run. We should implement properly configurable scheduling.

**Comment by sirewix** [comment]
What was the reason for having it on schedule in the first time? It shouldn't be that heavy to calculate, synapse sends a report each 3 hours, times the amount of homeservers, that doesn't seem to be that big amount of data. Maybe we can consider triggering aggregation on adding a report. Or on `/get_aggregated_stats` call, since it's just about 1 call per day which take a little longer than now, but it'll always return correct data

**Comment by emgrav** [comment]
Running it in response to `GET /aggregated-stats` will likely not work, there is still enough data that it takes a couple of minutes to run the aggregation each time. That said, running the aggregation statement multiple times a day will not have any effect each day will only be aggregated once. We can probably just turn down the timer to an hour or so
